### ISSUE TITLE
Adapting your seeds.js to sails0.10.x

### ISSUE THREAD

**Issue by davesag** [ericnograles/agilemoviedb#1]
Hi, I came across your project while searching for strategies for seeding my sails.js project with data it needs.  I am using Sails 0.10.x.

I've followed your example just fine (Thanks for the blog btw, it was educational), making changes where needed for Sails 0.10.x, but I am having issues with the following line

`new Movie({ adapters: { mongo: mongoAdapter }}, function(err, collection) {`

I just can't work out what needs to be there.

My `config/connections.js` looks like:

```
module.exports.connections = {
  development: {
    adapter  : 'sails-mongo',
    host     : 'localhost',
    port     : 27017,
    user     : 'myuser',
    password : 'mypass',
    database : 'mydb'
  }
};
```

and my `data/seeds.js` looks like

```
var _ = require("lodash"),
    Waterline = require("waterline"),
    connectionsConfig = require("../config/connections"),
    dbEnv = process.env.NODE_ENV || 'development',
    connection = connectionsConfig.connections[dbEnv],
    mongoAdapter = require(connection.adapter),
    Promise = require("promise"), mongoUrl;

console.log("connecting with ", connection);

// Match our config
mongoUrl = "mongodb://" +
            connection.user + ":" + connection.password + "@" +
            connection.host + ":" + connection.port + "/" +
            connection.database;

mongoAdapter.database = connection.database;
mongoAdapter.host =     connection.host;
mongoAdapter.port =     connection.port;
mongoAdapter.user =     connection.user;
mongoAdapter.password = connection.password;
mongoAdapter.config = {
  url: mongoUrl
};

/**
 * Seeds locations in a promise-y way
 */
var seedLocation = function() {
  console.log("seeding Locations");

  var LocationModel = require("../api/models/Location"),
      locationData = require("./locations.json");

  console.log("LocationModel", LocationModel);
  console.log("locationData", locationData.length);

  return new Promise(
    function(fulfill, reject) {
      // Seed Location Data from our JSON
      LocationModel.adapter = dbEnv;
      var Location = Waterline.Collection.extend(LocationModel);

      // Invoke Waterline
      new Location({ adapters: mongoAdapter }, function(err, collection) {
        if (err){
          console.error("There was a problem initializing the Location collection.");
        } else {
          // First nuke all existing Locations
          collection.destroy().done(function(err, deletedLocations) {
            console.log("Successfully deleted " + deletedLocations.length + " Locations!");
            collection.createEach(locationData, function(err, models) {
              if (err || _.isUndefined(models)) {
                console.log("Could not create Location collection!");
                fulfill();
              } else {
                console.log("Successfully inserted Locations");
                collection.find().done(function(err, existingLocations) {
                  fulfill(existingLocations);
                });
              }
            });
          });
        }
      });
    }
  );
};

// Node.js: fulfilling more promises than all politicians combined in history
seedLocation().then(function(locations) {
  console.log("Seeded" + locations.length + " locations");
  process.exit();
}, function(err){
  console.log("Seeding failed", err.stack);
});
```

The error I get is

```
Seeding failed TypeError: Cannot read property 'undefined' of undefined
    at Core._initialize (/Users/dave/src/myproject/node_modules/waterline/lib/waterline/core/index.js:70:47)
    at module.exports (/Users/dave/src/myproject/node_modules/waterline/lib/waterline/core/index.js:50:20)
    at module.exports (/Users/dave/src/myproject/node_modules/waterline/lib/waterline/collection/index.js:44:8)
    at new child (/Users/dave/src/myproject/node_modules/waterline/lib/waterline/utils/extend.js:17:39)
    at /Users/dave/src/myproject/data/seeds.js:45:32
    at new Promise (/Users/dave/src/myproject/node_modules/promise/index.js:42:5)
    at seedLocation (/Users/dave/src/myproject/data/seeds.js:38:10)
    at Object.<anonymous> (/Users/dave/src/myproject/data/seeds.js:71:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

I am using `waterline` version `0.10.0-rc9` and sails `0.10.0-rc8`

cheers and thanks in advance

dave

**Comment by ericnograles** [comment]
Hey Dave,

Sorry, just wanted to correct my solution to your issue as it was incomplete.

I believe the issue lies with these lines:

``` javascript
LocationModel.adapter = dbEnv;
```

``` javascript
new Location({ adapters: mongoAdapter }, function(err, collection) {
```

The LocationModel.adapter is actually a string reference to an adapter of the same name that is defined in line in the new Location() bit.

So, in my example, it looked like this:

``` javascript
MovieModel.adapter = 'mongo';
```

``` javascript
new Movie({ adapters: { mongo: mongoAdapter }}, function(err, collection) {
```

So, you'll see that we set the MovieModel's adapter to use a key called 'mongo', and in the constructor for the Model, we literally define an adapter called 'mongo' that is a reference to the mongoAdapter.

Adapting it to your approach, I'd imagine it'd look something like so...

``` javascript
LocationModel.adapter = 'mongo';
```

``` javascript
new Location({ adapters:{ mongo: mongoAdapter }}, function(err, collection) {
```

Give that a whirl and see if it stops barking at you.  Good luck!

Eric

**Comment by davesag** [comment]
Hi Eric, thanks for taking a look at this.

I tried the following as you suggested

```
  LocationModel.adapter = 'mongo';
  var Location = Waterline.Collection.extend(LocationModel);

  // Invoke Waterline
  new Location({ adapters: {mongo: mongoAdapter }}, function(err, collection) {
```

but I get the exact same error.

`seeds.js:45` is the `new Location…` line

**Comment by ericnograles** [comment]
HI Dave,

Maybe I should've looked at what version you were using first before I tried giving you advice  :)

Yes, it seems the approach above only works for v0.9.x Sails installs, as v0.10 has introduced a few new paradigms to connections and deprecated a few others.  I'll take it up with the Balderdashy guys and see if they have any examples, or check out the v0.10 beta of Waterline and see if that sheds any light.

**Comment by davesag** [comment]
Hi Eric,

I've poured over the waterline source but so far that's not helped me much.  I'll keep at this on the weekend and fire off some questions to Stackoverflow and the Sails.js google group.

Thanks

Dave

**Comment by ericnograles** [comment]
Sounds good, Dave.  I'll dig into v0.10.x myself sometime this weekend and see what I can find.  Surely, it must be something silly (I hope).

**Comment by davesag** [comment]
Hi Eric, I have worked it out.  Here's my final working `seed.js` file.

```
var _ = require("../node_modules/sails/node_modules/lodash"),
    setupWaterline = require('../node_modules/sails/node_modules/waterline/example/raw/bootstrap'),
    connectionsConfig = require("../config/connections"),
    dbEnv = process.env.NODE_ENV || 'development',
    connection = connectionsConfig.connections[dbEnv],
    mongoAdapter = require(connection.adapter),
    Promise = require("promise"), mongoUrl,
    locationData = require("./locations.json");

mongoUrl = "mongodb://" +
            connection.user + ":" + connection.password + "@" +
            connection.host + ":" + connection.port + "/" +
            connection.database;

mongoAdapter.defaults.database = connection.database;
mongoAdapter.defaults.host =     connection.host;
mongoAdapter.defaults.port =     connection.port;
mongoAdapter.defaults.user =     connection.user;
mongoAdapter.defaults.password = connection.password;
mongoAdapter.defaults.url =      mongoUrl;

// console.log("mongoAdapter", mongoAdapter);

setupWaterline({
  adapters: { mongo: mongoAdapter },
  collections: {
    location: {
      connection: 'tmp',
      attributes: {}
    }
  },
  connections: {
    tmp: {
      adapter: 'mongo'
    }
  }
}, function waterlineReady (err, ontology) {
  if (err) {
    throw err;
  }

  // Our collections (i.e. models):
  // ontology.collections;

  // Our connections (i.e. databases):
  // ontology.connections;

  seedLocation = function() {
    return new Promise(function(fulfill, reject) {
      var collection = ontology.collections.location;
      collection.destroy().exec(function(err, deletedLocations) {
        console.log("Successfully deleted " + deletedLocations.length + " Locations!");
        collection.createEach(locationData, function(err, models) {
          if (err || _.isUndefined(models)) {
            console.log("Could not create Location collection!");
            fulfill();
          } else {
            console.log("Successfully inserted Locations");
            collection.find().exec(function(err, existingLocations) {
              fulfill(existingLocations);
            });
          }
        });
      });
    });
  };

  seedLocation().then(function(locations) {
    console.log("Seeded", locations.length, "locations.");
    process.exit();
  }, function(err){
    console.log("Seeding failed", err.stack);
  });
});
```

It leverages a file within `Waterline`'s `examples/raw` folder called `bootstrap.js`

Thanks for your help, and I hope this is useful.

Dave

**Comment by ericnograles** [comment]
Excellent, Dave!  Yes, I was wondering if we could bypass some of the bootstrap.js stuff from the example, but I suppose not...great, find, and thanks for the follow-up!

Eric
